### ISSUE TITLE
Adjust for newest idea-based versions

### ISSUE THREAD

**Issue by andret2344** [mgziminsky/Minimap-for-Jetbrains#5]
Actual latest supported is 143.*, but latest stable is 203.*. Plugin cannot be loaded then

**Comment by mgziminsky** [comment]
Are you using the correct release? there are 2 versions, one for before v15, and one for v15+. I'll see about changing which one github is showing as the latest release

**Comment by mgziminsky** [comment]
Closing since it still works for me with the latest release of IntelliJ
